### ISSUE TITLE
what about data less than 6 items?

### ISSUE THREAD

**Issue by Nizar7zak** [GSG-G10/UR-History#32]
https://github.com/GSG-G10/UR-History/blob/12745139f532354a00eb295b4bd89b296a2829d6/public/js/fetchApi.js#L7

i think you should use Math.min when the user search about date and data response less than 6 items>

**Comment by umarsalah** [comment]
He will get the maximum number 6 so if there is less than 6 it will be the same the for loop will run 6 times with 

```js
[ {1},{2},{3},undefined,undefined]
